### ISSUE TITLE
Connect the API to pull gas station data

### ISSUE THREAD

**Issue by jawsh704** [mmlawton15/group-project-gas-guru#4]
- once zip code it submitted the gas stations will be pulled up 

- all gas station data will be stored some where (local storage)

**Comment by ghost** [comment]
due to the api being less than optimal, and only have limited apis to work with, we were only able to come up with only gas PRICES in ALL CITIES in NC. There is a limit on how many times we are allowed to access the data from the api as it is a "freemium" api.
